// This file contains the single source of truth for all biller data.
// To add, remove, or edit a biller, you only need to modify this file.

const billerData = [
    // ::: UPDATE: Removed the 'areaCodes' property from all biller objects :::
    { "id": 1, "isLive": true, "billerName": "CONSUMER ENERGY", "tla": "CEMI", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/display/CSR/CEMI+-+Consumers+Energy", "adLink": "https://adg-ipn1.paymentus.net/CEMI?v2=true", "ivrNumber": "866-329-9593", "csrNumber": "800-477-5050" },
    { "id": 2, "isLive": true, "billerName": "AUSTIN ENERGY", "tla": "AETX", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/display/CSR/AETX+-+Austin+Energy", "adLink": "https://adg-ipn1.paymentus.net/aetx?v2=true&lang=en", "ivrNumber": "833-375-4919", "csrNumber": "512-494-9400" },
    { "id": 3, "isLive": true, "billerName": "BALTIMORE GAS & ELECTRIC", "tla": "BGE", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/pages/viewpage.action?pageId=58165610", "adLink": "https://adg-ipn1.paymentus.net/bge?v2=true&lang=en", "ivrNumber": "1-833-254-9875", "csrNumber": "1-800-685-0123" },
    { "id": 4, "isLive": true, "billerName": "ATLANTIC CITY ELECTRIC", "tla": "PHI", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/pages/viewpage.action?pageId=58165643", "adLink": "https://adg-ipn1.paymentus.net/phi?v2=true&lang=en", "ivrNumber": "833-209-5484", "csrNumber": "800-642-3780" },
    { "id": 5, "isLive": true, "billerName": "DELMARVA POWER", "tla": "PHI", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/pages/viewpage.action?pageId=58165643", "adLink": "https://adg-ipn1.paymentus.net/phi?v2=true&lang=en", "ivrNumber": "833-209-5486", "csrNumber": "800-375-7117" },
    { "id": 6, "isLive": true, "billerName": "PEPCO", "tla": "PHI", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/pages/viewpage.action?pageId=58165643", "adLink": "https://adg-ipn1.paymentus.net/phi?v2=true&lang=en", "ivrNumber": "833-209-8415", "csrNumber": "202-833-7500" },
    { "id": 7, "isLive": true, "billerName": "AMERICAN WATER", "tla": "AWK", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/display/CSR/AWK+-+American+Water+Works+Company", "adLink": "https://adg-ipn1.paymentus.net/awk?v2=true&lang=en", "ivrNumber": "855-748-6066", "csrNumber": "(Refer KB link)" },
    { "id": 8, "isLive": true, "billerName": "COMD", "tla": "COMD", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/pages/viewpage.action?pageId=47000139", "adLink": "https://adg-ipn1.paymentus.net/COMD?v2=true", "ivrNumber": "800-588-9477", "csrNumber": "800-334-7661" },
    { "id": 9, "isLive": true, "billerName": "PACIFIC POWER/RMP", "tla": "PAC", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/display/CSR/PAC+-+PacifiCorp", "adLink": "https://adg-ipn1.paymentus.net/PAC?v2=true", "ivrNumber": "833-277-8689 RMP / 833-277-8690 PAC", "csrNumber": "888-221-7070" },
    { "id": 10, "isLive": true, "billerName": "GALVESTON", "tla": "GALV", "paymentType": "County Tax", "kbLink": "https://kb.paymentus.io/display/CSR/GALV+-+Galveston+County%2C+TX", "adLink": "https://adg-ipn1.paymentus.net/galv?v2=true&lang=en", "ivrNumber": "866-288-6894", "csrNumber": "877-766-2284" },
    { "id": 11, "isLive": false, "billerName": "Enbridge Solutions", "tla": "ESI", "paymentType": "Utilities", "kbLink": "https://paymentus.lightning.force.com/lightning/r/Opportunity/0067000000AINYwAAP/view", "adLink": null, "ivrNumber": "866-613-2531", "csrNumber": "(877) 362-7434" },
    { "id": 12, "isLive": false, "billerName": "City of Palm Coast, FL - Utility Bill", "tla": "PLMC", "paymentType": "Utilities", "kbLink": null, "adLink": "https://adg-ipn1.paymentus.net/plmc?v2=true&lang=en", "ivrNumber": "386 986-2360", "csrNumber": "386 986-2360" },
    { "id": 13, "isLive": false, "billerName": "City of Palm Coast, FL - Building Inspections", "tla": "PCBX", "paymentType": "Municipal", "kbLink": null, "adLink": "https://adg-ipn1.paymentus.net/pcbx?v2=true&lang=en", "ivrNumber": null, "csrNumber": "386 986-2360" },
    { "id": 14, "isLive": false, "billerName": "City of Palm Coast, FL - Miscellaneous Payments", "tla": "PCBM", "paymentType": "Municipal", "kbLink": null, "adLink": "https://adg-ipn1.paymentus.net/pcbm?v2=true&lang=en", "ivrNumber": null, "csrNumber": "386 986-2360" },
    { "id": 15, "isLive": false, "billerName": "City of Palm Coast, FL - Licensing Payments", "tla": "PCBP", "paymentType": "Municipal", "kbLink": null, "adLink": "https://adg-ipn1.paymentus.net/pcbp?v2=true&lang=en", "ivrNumber": null, "csrNumber": "386 986-2360" },
    { "id": 16, "isLive": false, "billerName": "Enbridge GAS OH", "tla": "DNE", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/pages/viewpage.action?pageId=58163398", "adLink": "https://adg-ipn1.paymentus.net/DNE?v2=true", "ivrNumber": "833-261-1469", "csrNumber": "800-362-7557 - 866-313-8303" },
    { "id": 17, "isLive": false, "billerName": "Pulaski County, Arkansas", "tla": "PVH4", "paymentType": "County Tax", "kbLink": null, "adLink": "https://adg-ipn1.paymentus.net/pvh4?v2=true&lang=en", "ivrNumber": "833-277-8725", "csrNumber": "501-340-6040" },
    { "id": 18, "isLive": false, "billerName": "Servicing Solutions, LLC", "tla": "SRVS", "paymentType": "Financial", "kbLink": null, "adLink": "https://adg-ipn1.paymentus.net/SRVS?v2=true", "ivrNumber": "833-894-0985", "csrNumber": "844-981-1370" },
    { "id": 19, "isLive": false, "billerName": "New York City Housing Authority (NYCHA)", "tla": "NYCH", "paymentType": "Housing", "kbLink": "https://kb.paymentus.io/pages/viewpage.action?pageId=195927148", "adLink": "https://adg-ipn1.paymentus.net/nych?v2=true&lang=en", "ivrNumber": "833-894-0899", "csrNumber": "718-707-7771" },
    { "id": 20, "isLive": false, "billerName": "City of Hollywood, FL", "tla": "HWFL", "paymentType": "Municipal", "kbLink": "https://kb.paymentus.io/display/CSR/HWFL+-+City+of+Hollywood%2C+FL", "adLink": "https://adg-ipn1.paymentus.net/hwfl?v2=true&lang=en", "ivrNumber": "855-748-4344", "csrNumber": "(954) 921-3938 option 5" },
    { "id": 21, "isLive": true, "billerName": "Hanover Insurance Co.", "tla": "HOIG", "paymentType": "Insurance", "kbLink": "https://kb.paymentus.io/pages/viewpage.action?pageId=10063113", "adLink": "https://adg-ipn1.paymentus.net/HOIG?v2=true", "ivrNumber": "800-573-1187", "csrNumber": "(800) 922-8427" },
    { "id": 22, "isLive": true, "billerName": "Horace Mann Insurance Company", "tla": "HRMN", "paymentType": "Insurance", "kbLink": "https://kb.paymentus.io/display/CSR/HRMN+-+Horace+Mann+Insurance+Company", "adLink": "https://adg-ipn1.paymentus.net/hrmn?v2=true&lang=en", "ivrNumber": "833-241-1608", "csrNumber": "800-999-1030" },
    { "id": 23, "isLive": true, "billerName": "Otter Tail", "tla": "OTPC", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/display/CSR/OTPC+-+Otter+Tail+Power+Company", "adLink": "https://adg-ipn1.paymentus.net/otpc?v2=true&lang=en", "ivrNumber": "866-377-1059", "csrNumber": "800-257-4044 or 218-739-8877" },
    { "id": 24, "isLive": true, "billerName": "American Intl Group/Lexington Ins", "tla": "AIGP", "paymentType": "Insurance", "kbLink": "https://kb.paymentus.io/pages/viewpage.action?pageId=195920329", "adLink": "https://adg-ipn1.paymentus.net/AIGP?v2=true", "ivrNumber": null, "csrNumber": "800-645-2259" },
    { "id": 25, "isLive": true, "billerName": "Puget Sound Energy", "tla": "PSE", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/display/CSR/PSE+-+Puget+Sound+Energy", "adLink": "https://adg-ipn1.paymentus.net/PSE?v2=true", "ivrNumber": "1-888-225-5773", "csrNumber": "1-888-225-5773" },
    { "id": 26, "isLive": false, "billerName": "Atmos Energy", "tla": "ATM", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/pages/viewpage.action?pageId=128081605", "adLink": "https://adg-ipn1.paymentus.net/ATM?v2=true", "ivrNumber": null, "csrNumber": "888-286-6700" },
    { "id": 27, "isLive": false, "billerName": "Hawaiian Electric", "tla": "HAWE", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/pages/viewpage.action?pageId=100934635", "adLink": "https://adg-ipn1.paymentus.net/hawe?v2=true&lang=en", "ivrNumber": "888-826-5006", "csrNumber": "Oahu (808) 548-7311, Maui (808) 871-9777, Hilo (808) 969-6999" },
    { "id": 28, "isLive": false, "billerName": "Arizona Public Service", "tla": "APS", "paymentType": "Utilities", "kbLink": "https://kb.paymentus.io/display/CSR/APS+-+Arizona+Public+Service", "adLink": "https://adg-ipn1.paymentus.net/aps?v2=true&lang=en", "ivrNumber": "833-970-2343", "csrNumber": "(800) 253-9405" },
    { "id": 29, "isLive": false, "billerName": "Rocky View County AB", "tla": "RVCT", "paymentType": "County Services", "kbLink": null, "adLink": "https://adg-ipn1.paymentus.net/rvct?v2=true&lang=en", "ivrNumber": null, "csrNumber": "403-230-1401" }

];
